### ISSUE TITLE
How do I parse all LDOs that match a schema out of a dataset?

### ISSUE THREAD

**Issue by ianconsolata** [o-development/ldo-legacy#1]
Most of your examples show parsing a single LDO from a dataset by subject (similar to Inrupt's `getThing` function on a `SolidDataset`).

We frequently use Datasets as collections, and need to pull out all Things / LDOs from a given dataset. Is there a way to do that with LDO?

If not, I think the LDOFactory could include a `parseAll` method that would operate similar to `getThingAll` and parse all LDOs from a dataset that match the given shex schema.

**Comment by jaxoncreed** [comment]
At the moment, there is no Query or Match function in LDO. That's something that I plan on adding in the future.

**Comment by jaxoncreed** [comment]
LDO's most recent update now has a feature for this. The [`matchSubject`](https://github.com/o-development/ldo#matchsubjectpredicate-object-graph) and [`matchObject`](https://github.com/o-development/ldo#matchobjectsubject-predicate-object) constructors will allow you select an array of items as if you were using the `match` method from RDF JS.
