### ISSUE TITLE
Support language tags

### ISSUE THREAD

**Issue by mrkvon** [o-development/ldo-legacy#13]
This is a feature request, or a question:

Is it currently possible to read and update a string with language tag, e.g. `"some text"@en`?

In my shex, i specified:

```
foo:predicate rdf:langString* ;
```
and with it, i was able to read value of the string, and save a new language string as `"some text"^^rdf:langString`, but i haven't found a way to read or set the language.

I'd like the input to include current language string, and output to be in form `"some text"@en`.

Is it possible? If it is, how can it be done? If not, this is a feature request. 🙂

**Comment by jaxoncreed** [comment]
Unfortunately, I don't have support for language tags. This is a feature I hope to implement in the future.

**Comment by jaxoncreed** [comment]
Support for language tags is now added in v1.0.3. See documentation for how to use it here: https://github.com/o-development/jsonld-dataset-proxy#managing-language-tags
