### ISSUE TITLE
No foafProfile.ldoFactory.ts

### ISSUE THREAD

**Issue by tranbau** [o-development/ldo-legacy#20]
why when i try npm run build:ldo i got 4 file except foafProfile.ldoFactory.ts

**Comment by mrkvon** [comment]
I think it's because ldo v1 doesn't use the factory for anything, so ldo-cli v3 doesn't export it. Version 0 used it, and ldo-cli v2 exported it. I only discovered it now, thanks to your comment. Maybe @jaxoncreed can confirm if this is the case...

So my guess is, this is an expected behavior.

**Comment by jaxoncreed** [comment]
@tranbau @mrkvon. That's true. The factory is no longer used. If you want to use older versions of LDO then be sure your instance of ldo-cli is under 3.

**Comment by tranbau** [comment]
[jaxoncreed](https://github.com/jaxoncreed) Coming from SolidForum :) Thank you for the answer!
